<!-- PORTFOLIO UNIT -->
<?php echo $this->render("index/portfolio.phtml"); ?>
<!--/PORTFOLIO UNIT  -->

<!-- PARALLAX DIALOGUE UNIT-->
<?php echo $this->render("index/parallax.phtml"); ?>
<!--/PARALLAX DIALOGUE UNIT-->

<!-- ABOUT UNIT -->
<?php echo $this->render("index/about.phtml"); ?>
<!-- /ABOUT UNIT -->
<!-- TESTIMONIALS -->
<?php echo $this->render("index/testimonials.phtml"); ?>
<!--/TESTIMONIALS -->

<!-- FEATURES UNIT -->
<?php echo $this->render("index/features.phtml"); ?>
<!--/FEATURES UNIT  -->

<!-- SIGNUP -->
<?php echo $this->render("index/signup.phtml"); ?>

<!--/SIGNUP -->







<!-- SOCIAL BAR -->
<?php echo $this->render("index/socialbar.phtml"); ?>
<!--/SOCIAL BAR -->

<!-- CONTACT-US -->
<?php echo $this->render("index/contact.phtml"); ?>
<!--/CONTACT-US -->
<!-- TEAM UNIT -->
<?php // echo $this->render("index/team-unit.phtml"); ?>
<!--/TEAM UNIT  -->
