<aside>
    <div class="top">
        <nav>
            <ul class="collapsible accordion">


                <li class="dashboard-menu"><a href="#"><span class="icon icon_16 dashboard"></span>Dashboard</a></li>
                <li class="locacoes">
                    <a href="javascript:void(0);" class="locacoes"><span class="icon icon_16 home-for-sale-sign"></span>Locações</a>
                    <ul>

                        <li class="ativas"><a href="#locacoes/ativas"><span class="icon icon_16 tick-octagon"></span>Locações Ativas</a></li>
                        <li class="concluidas"><a href="#locacoes/concluidas"><span class="icon icon_16 tick-white"></span>Locações Concluídas</a></li>
                        <li class='divider'></li>
                        <li class="cadastro"><a href="#locacoes/cadastro"><span class="icon icon_16 home--plus"></span>Nova Locação</a></li>
                        <li class="devolucao"><a href="#locacoes/devolucao"><span class="icon icon_16 arrow-return-180-left"></span>Devolução</a></li>
                        <li class="renovacao"><a href="#locacoes/renovacao"><span class="icon icon_16 hourglass--plus"></span>Renovação</a></li>
                        <li class='divider'></li>
                        <li class="comprovantes"><a href="#locacoes/comprovantes"><span class="icon icon_16 zone--pencil"></span>Comprovantes</a></li>


                    </ul>
                </li>
                <li class="clientes">
                    <a href="javascript:void(0);" class="clientes"><span class="icon icon_16 user-green"></span>Clientes</a>
                    <ul class="">
                        <li class="listagem"><a href="#clientes/listagem"><span class="icon icon_16 table"></span>Listagem</a></li>
                        <li class="cadastro"><a href="#clientes/cadastro"><span class="icon icon_16 user--plus"></span>Novo Cliente</a></li>
                        <li class='divider'></li>
                        <li class="co-responsabilidade"><a href="#clientes/co-responsabilidade"><span class="icon icon_16 user-detective"></span>Co-Responsabilidade</a></li>
                        <li class='divider'></li>
                        <li class="cobranca"><a href="#clientes/cobranca"><span class="icon icon_16 money-coin"></span>Cobrança</a></li>



                    </ul>
                </li>

                <li class="equipamentos">
                    <a href="javascript:void(0);" class="equipamentos"><span class="icon icon_16 drill"></span>Equipamentos</a>
                    <ul>
                        <li class="listagem"><a href="#equipamentos/listagem"><span class="icon icon_16 table"></span>Listagem</a></li>
                        <li class="cadastro"><a href="#equipamentos/cadastro"><span class="icon icon_16 drill--plus"></span>Novo Equipamento</a></li>
                        <li class='divider'></li>
                        <li class="categorias"><a href="#equipamentos/categorias"><span class="icon icon_16 edit-list-order"></span>Categorias</a></li>
                        <li class="modelos"><a href="#equipamentos/modelos"><span class="icon icon_16 script-attribute-m"></span>Modelos</a></li>
                        <li class="acessorios"><a href="#equipamentos/acessorios"><span class="icon icon_16 headphone"></span>Acessórios</a></li>

                        <li class='divider'></li>
                        <li class="manutencao"><a href="#equipamentos/manutencao"><span class="icon icon_16 wrench-screwdriver"></span>Manutenção</a></li>
                        <li class="estoque"><a href="#equipamentos/estoque"><span class="icon icon_16 report--plus"></span>Estoque</a></li>

                    </ul>
                </li>

                <li class="fornecedores">
                    <a href="javascript:void(0);" class="fornecedores"><span class="icon icon_16 user-worker-boss"></span>Fornecedores</a>
                    <ul>
                        <li class="listagem"><a href="#fornecedores/listagem"><span class="icon icon_16 table"></span>Listagem</a></li>
                        <li class="cadastro"><a href="#fornecedores/cadastro"><span class="icon icon_16 user-worker"></span>Novo Fornecedor</a></li>



                    </ul>
                </li>
                <li class="obras">
                    <a href="javascript:void(0);" class="obras"><span class="icon icon_16 hard-hat"></span>Obras</a>
                    <ul>

                        <li class="listagem"><a href="#obras/listagem"><span class="icon icon_16 table"></span>Listagem</a></li>
                        <li class="cadastro"><a href="#obras/cadastro"><span class="icon icon_16 hard-hat--plus"></span>Nova Obra</a></li>


                    </ul>
                </li>
                <li class="relatorios">
                    <a href="javascript:void(0);" class="relatorios"><span class="icon icon_16 report"></span>Relatórios</a>
                    <ul>

                        <li class="clientes"><a href="#relatorios/clientes"><span class="icon icon_16 report-paper"></span>Clientes</a></li>
                        <li class="co-responsabilidades"><a href="#relatorios/co-responsabilidades"><span class="icon icon_16 report-paper"></span>Co-Responsabilidade</a></li>
                        <li class="cobrancas"><a href="#relatorios/cobrancas"><span class="icon icon_16 report-paper"></span>Cobranças</a></li>
                        <li class="obras"><a href="#relatorios/obras"><span class="icon icon_16 report-paper"></span>Obras</a></li>

                        <li class='divider'></li>
                        <?php /*
                          <li class="equipamentos"><a href="#relatorios/equipamentos"><span class="icon icon_16 report-paper"></span>Equipamentos</a></li>
                          <li class="categorias"><a href="#relatorios/categorias"><span class="icon icon_16 report-paper"></span>Categorias</a></li>
                          <li class="modelos"><a href="#relatorios/modelos"><span class="icon icon_16 report-paper"></span>Modelos</a></li>
                          <li class="acessorios"><a href="#relatorios/acessorios"><span class="icon icon_16 report-paper"></span>Acessórios</a></li>

                          <li class='divider'></li>
                          <li class="locacoes"><a href="#relatorios/locacoes"><span class="icon icon_16 report-paper"></span>Locações</a></li>
                          <li class="devolucoes"><a href="#relatorios/devolucoes"><span class="icon icon_16 report-paper"></span>Devoluções</a></li>

                          <li class='divider'></li>
                          <li class="fornecedores"><a href="#relatorios/fornecedores"><span class="icon icon_16 report-paper"></span>Fornecedores</a></li>
                         */ ?>
                    </ul>
                </li>
                <li class="usuarios">
                    <a href="javascript:void(0);" class="usuarios"><span class="icon icon_16 users"></span>Usuários</a>
                    <ul >
                        <li class="listagem"><a href="#usuarios/listagem"><span class="icon icon_16 table"></span>Listagem</a></li>
                        <li class="cadastro"><a href="#usuarios/cadastro"><span class="icon icon_16 user--plus"></span>Novo Usuário</a></li>
                        <li class='divider'></li>
                        <li class="grupos"><a href="#usuarios/grupos"><span class="icon icon_16 user-silhouette-question"></span>Grupos</a></li>
                    </ul>
                </li>
                <li class="configuracoes">
                    <a href="javascript:void(0);" class="configuracoes"><span class="icon icon_16 gear"></span>Configurações</a>
                    <ul>

                        <li class="contrato"><a href="#configuracoes/contrato"><span class="icon icon_16 script--pencil"></span>Contrato</a></li>
                        <li class="empresa"><a href="#configuracoes/empresa"><span class="icon icon_16 property-blue"></span>Dados Empresa</a></li>
                        <li class="unidades"><a href="#configuracoes/unidades"><span class="icon icon_16 wooden-box"></span>Unidades</a></li>
                        <li class="backup"><a href="#configuracoes/backup"><span class="icon icon_16 database-export"></span>Backup</a></li>



                    </ul>
                </li>


            </ul>
        </nav>
    </div>

</aside>