<!doctype html>
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Aplicativo Alicerce Locação</title>
        <meta name="description" content="Coringa Sistemas Administrativos, responsive Admin Template build with modern techniques like HTML5 and CSS3 to be used for backend solutions of any size.">
        <meta name="author" content="Coringa Sistemas">
        <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="format-detection" content="telephone=no">
        <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
        <?php echo $this->headLink(); ?>
        <script src="<?php echo $this->baseUrl('/js/alicerce/jquery.min.js') ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/alicerce/jquery-ui.min.js') ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/alicerce/lo-dash.min.js') ?>"></script>
        <script type="text/javascript" src="/js/admin/plugins/jquery.blockUI.min.js"></script>

        <?php echo $this->headScript(); ?>
        <script src="/minify/javascript" type="text/javascript"></script>
        <script type="text/javascript">
            window.WebFontConfig = {
                google: {families: ['PT Sans:400,700']},
                active: function() {
                    $(window).trigger('fontsloaded')
                }
            };

        </script>
        <script src="<?php echo $this->baseUrl('/js/alicerce/mylibs/polyfills/respond.js') ?>"></script>

    </head>

    <body>

        <?php echo $this->render('layouts/toolbar.phtml'); ?>

        <?php echo $this->render('layouts/header.phtml'); ?>


        <div role="main" id="main" class="container_12 clearfix">
            <?php echo $this->render('layouts/tool.phtml'); ?>
            <?php echo $this->render('layouts/aside.phtml'); ?>
            <div class='content-page'></div>
            <?php //echo $this->layout()->content ?>
        </div>
        <?php echo $this->render('layouts/footer.phtml'); ?>


        <script>
            $(function() {
                $$.loaded();

            })

        </script>
    </body>
</html>