<div id="loading-overlay"></div>
<div id="loading">
    <span>Carregando...</span>
</div>
<div id="lock-screen" title="Proteção de Tela" style="padding:10px">
    <a href="login.html" class="header right button grey flat">Sair</a>
    <p>Devido a inatividade na página sua seção foi bloqueada.</p>
    <p>Para desbloquear sua conta, deslize o botão e digite sua senha.</p>
    <div class="actions">
        <div id="slide_to_unlock">
            <img src="/img/admin/elements/slide-unlock/lock-slider.png" alt="slide me">
            <span>Deslize o botão</span>
        </div>
        <form action="#" method="GET">
            <input type="password" name="pwd" id="pwd" placeholder="Digite sua senha..." autocorrect="off" autocapitalize="off">
            <input type="submit" name=send value="Ok" disabled>
            <input type="reset" value="X">
        </form>
    </div>
</div>