<section class="toolbar">
    <div class="user">
        <div class="avatar">
            <img src="/img/alicerce/layout/content/toolbar/user/avatar.png">
            <span class="totalmsgs perfil" style="display:none"></span>
        </div>
        <span><?php echo ucwords($_SESSION['auth']['username']) ?></span>
        <ul>

            <li><a href="/login/index/logout">Sair</a></li>
        </ul>
    </div>
    <?php /*
      <ul class="shortcuts">
      <li>
      <a href="javascript:void(0);"><img class="icon" src="/img/alicerce/icons/packs/fugue/24x24/home-for-sale-sign.png" /></a>
      <div class="small">
      <h3>Locações</h3>
      <div class="content" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active');
      location.hash = '#locacoes/cadastro'">
      <strong><span class="icon icon_16 home--plus"></span>Nova Locação</strong>
      </div>
      <div class="content" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active');
      location.hash = '#locacoes/ativas'">
      <strong ><span class="icon icon_16 tick-octagon"></span>Locações Ativas</strong>
      </div>
      <div class="content" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active');
      location.hash = '#locacoes/concluidas'">
      <strong ><span class="icon icon_16 tick-white"></span>Locações Concluídas</strong>
      </div>
      <div class="content" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active');
      location.hash = '#locacoes/devolucao'">
      <strong ><span class="icon icon_16 arrow-return-180-left"></span>Devoluções</strong>
      </div>
      <div class="content" onclick="$(this).parent().fadeToggle($$.config.fxSpeed).parent().removeClass('active');
      location.hash = '#locacoes/renovacao'">
      <strong ><span class="icon icon_16 hourglass--plus"></span>Renovações</strong>
      </div>
      </div>
      </li>
      <li>
      <a href="javascript:void(0);"><img class="icon" src="/img/alicerce/icons/packs/fugue/24x24/user-green.png" /></a>
      <div class="small">
      <h3>Clientes</h3>

      </div>
      </li>
      <li>
      <a href="javascript:void(0);"><img class="icon" src="/img/alicerce/icons/packs/fugue/24x24/drill.png" /></a>
      <div class="small">
      <h3>Equipamentos</h3>

      </div>
      </li>
      <li>
      <a href="javascript:void(0);"><img class="icon" src="/img/alicerce/icons/packs/fugue/24x24/user-worker-boss.png" /></a>
      <div class="small">
      <h3>Fornecedores</h3>

      </div>
      </li>
      </ul>
     */ ?>


</section>
