<!-- Showing the image clouds, stars, and moon -->
    <div id="clouds"></div>
    <div id="stars"></div>
    <div id="moon"></div>

    <!-- BEGIN CONTENT -->
    <div class="wrap_content">
      <h1>Sessão Encerrada.</h1>
      <h2>Essa não! Está escuro aqui.</h2><br/>
      <p>Sua sessão expirou para sua segurança. Entre novamente no sistema para iniciar uma nova sessão.</p>
      <p>Tente retornar para a <a href="/">página principal</a> e entrar novamente no sistema.</p>
    </div><!-- End div content -->
    <!-- END CONTENT -->

    <!-- BEGIN BOTTOM -->
    <div class="wrap_bottom">
      <div id="tumbleweed"></div>
      <div class="image_wrapper">
        <div id="house"></div>
      </div>
    </div><!-- End div content -->
    <!-- END CONTENT -->

    <!-- BEGIN FOOTER -->
    <div class="wrap_footer">
      <div class="content_footer">
      
      </div>
    </div><!-- End div footer -->
    <!-- END FOOTER -->
    

