<section id="content" class="container_12 clearfix" data-sort="true">
    <h1 class="grid_12">Configurações do Contrato</h1>
    <form name="fm_obras" id="fm_obras" action="/configuracoes/contrato" class="grid_12 validate" method="post">
        <fieldset>
            <legend>Contrato</legend>
            <div class="row inphone" >
                <label for='termo_contrato' class="nophone">Termos do Contrato</label>
                <div>
                    <textarea class='editorfull' name='termo_contrato' id='termo_contrato' style="width:100%; height:500px">
                        <?php echo $this->config['termo_contrato']; ?>
                    </textarea>
                </div>
            </div>
            <div class="row inphone" >
                <label for='testemunha' class="nophone">Observações do Contrato</label>
                <div>
                    <textarea class='editorfull' name='obs_contrato' id='obs_contrato' style="width:100%; height:500px">
                        <?php echo $this->config['obs_contrato']; ?>
                    </textarea>
                </div>
            </div>
            <div class='buttons-box'>
                <button class='button green'><span class='icon icon-save'></span>Salvar Alterações</button>
                <button class='button red' onclick='location.hash = "";
                        return false;'><span class='icon icon-remove-circle'></span>Cancelar</button>

            </div>
        </fieldset>
    </form>
</section>
<script>
    setTimeout(function() {
        $("textarea").each(function() {
            var l = $(this), k = l.hasClass("full");

            l.cleditor({width: k ? "auto" : "100%", height: "600px", bodyStyle: "margin: 10px; font: 12px Arial,Verdana; cursor:text", useCSS: true});
            k && l.parents(".cleditorMain").addClass("full")

        });
    }, 200);
</script>