<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->

<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt_BR"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Autenticação Nutrace</title>
        <meta name="description" content="Nutrace">
        <meta name="author" content="RoDa Sistemas">
        <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="format-detection" content="telephone=no">

        <link rel="shortcut icon" href="/img/favicon.ico" />
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
        <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->


        <!-- The Styles -->
        <!-- ---------- -->

        <!-- Layout Styles -->
        <?php echo $this->headLink(); ?>




        <!-- The Scripts -->
        <!-- ----------- -->

        <script src="<?php echo $this->baseUrl('/js/login/jquery.min.js') ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/login/jquery-ui.min.js') ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/login/lo-dash.min.js') ?>"></script>
        <script type="text/javascript" src="/js/login/plugins/jquery.blockUI.min.js"></script>
        

        <!-- JavaScript at the top (will be cached by browser) -->

        <!-- Load Webfont loader -->
        <script type="text/javascript">
            window.WebFontConfig = {
                google: {families: ['PT Sans:400,700']},
                active: function() {
                    $(window).trigger('fontsloaded')
                }
            };
        </script>

        <?= $this->headScript() ?>

        <!-- end scripts -->

    </head>

    <body class=login>
        <!-- Some dialogs etc. -->

        <!-- The loading box -->

        <!-- End of loading box -->

        <!--------------------------------->
        <!-- Now, the page itself begins -->
        <!--------------------------------->

        <!-- The toolbar at the top -->
        <?php echo $this->render('layout/toolbar-top.phtml'); ?>
        <!-- End of #toolbar -->

        <!-- The header containing the logo -->
        <?php echo $this->render('layout/header.phtml'); ?>
        <!-- End of header -->

        <!-- The container of the sidebar and content box -->
        <?php echo $this->layout()->content ?>
        <script src="/login/minify/javascript" type="text/javascript"></script>
        <!-- Spawn $$.loaded -->
        <script>
            $$.loaded();
        </script>

        <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
           chromium.org/developers/how-tos/chrome-frame-getting-started -->
        <!--[if lt IE 7 ]>
        <script defer src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
        <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
        <![endif]-->

    </body>
</html>

