<div class="container">
    <div class="row">
        <div id="content" class="col-lg-12">
            <!-- PAGE HEADER-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header">
                        <!-- STYLER -->

                        <!-- /STYLER -->
                        <!-- BREADCRUMBS -->
                        <ul class="breadcrumb">
                            <li>
                                <i class="fa fa-home"></i>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <a href="#">Other Pages</a>
                            </li>
                            <li>Blank Page</li>
                        </ul>
                        <!-- /BREADCRUMBS -->
                        <div class="clearfix">
                            <h3 class="content-title pull-left">Blank Page</h3>
                        </div>
                        <div class="description">Blank Page</div>
                    </div>
                </div>
            </div>
            <!-- /PAGE HEADER -->
        </div>
    </div>
</div>
