<table class="table table-paper table-striped" id="example-paper">
    <tbody>
        <?php
        foreach ($this->feeds as $feed) {
            $d_h = explode("T", $feed->getUpdated());
            $d = explode('-', $d_h[0]);
            $data_hora = $d[2] . '/' . $d[1] . '/' . $d[0];
            $videoThumbnails = $feed->getVideoThumbnails();
            $views = $feed->getVideoViewCount();
            ?>
            <tr data-id="<?php
            $id = explode('/', $feed->getId());
            echo $id[count($id) - 1];
            ?>" data-link="<?php echo $feed->getVideoWatchPageUrl(); ?>">
                <td class='col-min'>
                    <img src='<?php echo $videoThumbnails[0]['url']; ?>' class='img_player' />
                </td>
                <td>
                    <div class='video_title'><?php echo $feed->getVideoTitle(); ?></div>
                    <div class='video_date'>
                        <i class="fa fa-calendar-o"></i>
                        <time  class='timeago' datetime="<?php echo $d_h[0]; ?>"></time >
                    </div>
                    <div class='video_views'><i class="fa fa-eye"></i> <?php echo $views; ?> Visualizações</div>
                    <div class='video_duration'><i class="fa fa-clock-o" title='Duração'></i> <?php echo gmdate("i:s", $feed->getVideoDuration()) ?></div>
                    <div class="clearfix"></div>
                    <div class="panel-body">
                        <div class='video_description'><?php echo $feed->getVideoDescription(); ?></div>
                    </div>
                </td>
                <td class='col-min'>
                    <button class='btn btn-xs btn-success use-video'> <i class='fa fa-arrow-circle-o-left'></i> Usar</button>

                </td>
                <td class='col-min'>
                    <button class='btn btn-xs btn-default preview-yt'> <i class='fa fa-eye'></i> Previsualizar</button>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<script>
    $(document).ready(function() {
        coringa.youtube();
    });
</script>
