<div class="box-body">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Atenção!</h3>
        </div>
        <div class="panel-body">
            <p>Vídeos enviados para o Youtube necessitam de análise e conversão de formatos que são realizados pelo próprio Youtube.<br/>
                Com isso os vídeos enviados podem não ser disponibilizados automaticamente ou na finalização do envio.</p>
            <form id="fm_yt" name="fm_yt" action="<?php echo $this->postUrl . '?nexturl=' . $this->nextUrl ?>" method="post" enctype="multipart/form-data">
                <div class="fileinput fileinput-new" data-provides="fileinput">

                    <div class="input-group">
                        <div class="form-control uneditable-input" data-trigger="fileinput">

                            <span class="fileinput-preview"><i class="glyphicon glyphicon-file fileinput-exists"></i></span>
                            <span class="fileinput-filename">
                                Selecione um Vídeo.
                            </span>

                        </div>
                        <div class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Selecionar Vídeo</span>
                                <span class="fileinput-exists">Mudar</span>
                                <input type="file" class="file-input" name="file_yt" id="file_yt" accept="video/*" />
                                <input name="token" type="hidden" value="<?php echo $this->tokenValue ?>"/>

                            </span>
                            <button href="#" class="btn btn-success fileinput-exists" id="but_yt_enviar">Enviar Vídeo</button>
                            <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remover</a>

                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="panel-footer">
            <div class="form-group" id="prgb" style="display: none">
                <h4 class="percent-status"></h4>
                <div class="progress progress-striped active">
                    <span class="sr-only percent"></span>
                    <div class="progress-bar bar envio_bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">

                    </div>
                </div>
            </div>
            <div id="status">


            </div>
        </div>
    </div>



</div>
<script>


    $('#fm_yt').ajaxForm({
        beforeSend: function() {
            $('#but_yt_enviar').attr('disabled', 'disabled');
            //$('#status').empty();
            var percentVal = '0%';
            $('#prgb').show('slow');
            //  $('.envio_bar').html(percentVal);
            $(".percent-status").html('Aguardando envio para o Youtube.');
            $('.percent').progressbar({value: 0});

        },
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            $(".percent-status").html(percentComplete + '% enviados para o Youtube.');
            // $('.envio_bar').html(percentVal);
            $('.percent').progressbar({value: percentComplete});
            $(".envio_bar").attr("style", "width:" + percentComplete + "%");
        },
        complete: function() {
            $('.envio_bar').html('Concluído!');
            $(".percent-status").html('Vídeo enviado para o Youtube com sucesso.');
            $('.percent').progressbar({value: 100});
            $(".envio_bar").attr("style", "width:100%");
            $.ajax({
                url: '/artigos/youtube',
                type: 'get',
                success: function(data) {
                    $("#box_tab1").html(data);
                }
            })
        }
    });



</script>





