<header class="container_12">

    <div class="container">

        <!-- Your logos -->
        <a href="http://www.coringasistemas.com.br/" target="_blank">
            <img src="<?php echo $this->baseUrl('/img/admin/logo.png') ?>" alt="Coringa Sistemas">
        </a>
        <a class="phone-title" href="/login">
            <img src="<?php echo $this->baseUrl('/img/admin/logo.png') ?>" alt="Coringa Sistemas" />
        </a>

        <!-- Right link -->
        <div class="right">
            <span>Não tem uma conta ainda?</span>
            <a href="javascript:void(0);">Registrar</a>
        </div>

    </div><!-- End of .container -->

</header>