<section id="toolbar">
    <div class="container_12">

        <!-- Left side -->
        <div class="left">
            <ul class="breadcrumb">

                <li><a href="javascript:;" class="active"><?php echo $this->controle; ?></a></li>
                <li><a href="/login">Login</a></li>

            </ul>
        </div>
        <!-- End of .left -->

        <!-- Right side -->
        <div class="right">
            <ul>



                <li class="red"><a target="_blank" href="#">Reportar Erro</a></li>

            </ul>
        </div><!-- End of .right -->

        <!-- Phone only items -->
        <div class="phone">

            <!-- User Link -->
            <li><a href="#"><span class="icon icon-home"></span></a></li>
            <!-- Navigation -->
            <li><a href="#"><span class="icon icon-heart"></span></a></li>

        </div><!-- End of .phone -->

    </div><!-- End of .container_12 -->
</section>