<section id="content" class="container_12 clearfix " data-sort="true">
    <div class='grid_12'>
        <div class='box'>
            <div class='header'>
                <h2>Dados de Contato</h2>
            </div>
            <div class='content' style='padding:10px; font-size:18px; line-height: 150%'>

                <strong>Telefone:</strong>(34) 3242-3915<br/>
                <strong>Celular:</strong>(34) 8812-7312(Oi)<br/>
                <strong>Email:</strong> <a href="mailto:email@rodrigodaniel.com.br">email@rodrigodaniel.com.br</a><br/>

            </div>
        </div>
</section>