<section id="content" class="container_12 clearfix" data-sort="true">
    <div>
        <div class="searchbox grid_12">
            <input type="text" placeholder="Digite aqui sua dúvida..."/>
            <input type="submit" value="Pesquisar" class=grey />
        </div>
        <h1 class="grid_12 margin-top">Perguntas Frequentes (FAQ)</h1>
        <div class="vertical-tabs grid_12">

            <p class="grid_12">Aqui se encontram as principais perguntas e respostas sobre o funcionamento e manuseio do sistema em geral.</p>
            <div class="accordion toggle grid_12 border">
                <h3><a href="javascript:void(0);">O que é e pra que serve o Dashboard?</a></h3>
                <div>
                    <p>O Dashboard é a tela principal do sistema onde as informações principais do sistema são demonstradas de várias formas, são elas:
                    <ul>
                        <li>
                            Através de Notificações
                        </li>
                        <li>
                            Através de Quantidades de Registros, Estoques, Locados e em Manutenção
                        </li>
                        <li>
                            Gráfico de Equipamentos de maior saída no mês
                        </li>
                        <li>
                            Agenda de Retornos de Locações e Compromissos
                        </li>
                    </ul>
                    </p>
                    <p>
                        Também na tela principal (Dashboard), é possível acessar rapidamente os cadastro principais atraves dos botões de menu da caixa Cadastro.
                    </p>
                </div>
                <h3><a href="javascript:void(0);">Como cadastro um cliente?</a></h3>
                <div>
                    <p>O sistema é separado por menus de controle específico que fica posicionado à esquerda do sistema</p>
                    <p>Para cadastrar um novo cliente basta acessar o menu <strong>Clientes</strong> e clicar na opção <strong>Novo Cliente</strong>.</p>
                    <p>O formulário para cadastro é automatizado no campo de <strong>CEP</strong> para preenchimento do endereço do cliente. Apenas os campos de <strong>RG/Insc. Estadual</strong> e <strong>Celular</strong> são opcionais, o restante é obrigatório.</p>
                    <p>Ao salvar um novo cliente este já estará apto à receber uma locação.<br/>Com o cliente cadastrado é opcional o cadastro de Responsáveis pelo cliente, cadastro de Obras e endereços de Cobrança, sendo que os mesmos se não forem cadastrados terão o mesmo conteúdo do cliente.</p>
                    <p>O preenchimento do email é importante para o envio de mala diretas e avisos que o sistema pode emitir, tornando a interatividade do sistema mais completa e objetiva.</p>
                    <p>Caso tenha digitado algum dado errado no cadastro do cliente, é possível alterar os dados através da <strong>Listagem</strong> no menu <strong>Clientes</strong>. Bastando para isso selecionar o registro incorreto e logo depois clicar no botão <strong>Editar Registro</strong>.</p>
                    <p>Se tiver necessidade de excluir um cliente o mesmo poderá ser feito através da <strong>Listagem</strong> no menu <strong>Clientes</strong>, como no processo anterior basta selecionar o registro desejado e clicar no botão <strong>Excluir Registro</strong>.</p>
                </div>
                <h3><a href="javascript:void(0);">Como cadastro um Equipamento?</a></h3>
                <div>
                    <p>O sistema é separado por menus de controle específico que fica posicionado à esquerda do sistema</p>
                    <p>Para cadastrar um novo cliente basta acessar o menu <strong>Equipamentos</strong> e clicar na opção <strong>Novo Equipamento</strong>.</p>
                    <p>O cadastro de equipamentos depende do cadastro de <b>Categorias</b> préviamente, assim como também o cadastro de <b>Modelos</b> e <b>Fornecedores</b>, sendo que esses dois últimos ítens são opcionais.<br/>
                        O cadastro de Categorias e Modelos pode ser realizado no menu <b>Equipamentos</b>, já o cadastro de Fornecedores possui um menu próprio <b>Fornecedores</b> e a opção <b>Novo Fornecedor</b>. Os Fornecedores também necessitam do cadastro de Categorias previamente realizado.</p>
                    <p>No formulário do Equipamento somente o campo de <b>Modelos</b> e <b>Fornecedores</b> são opcionais, todos os demais são obrigatórios.<br/>
                        No campo <b>Quantidade de Equipamentos</b> é necessário informar a quantidade em Estoque Efetivo para o equipamento em questão, assim como sua unidade padrão. As <b>Unidades</b> podem ser alteradas no menu <b>Configurações</b> na opção <b>Unidades</b>.</p>
                    <p>O <b>Valor de Locação</b> é referente ao valor Mensal da locação do Equipamento.</p>
                    <p>No campo de <b>Imagem</b> do equipamento é possível adicionar quantas imagens forem necessárias. Basta clicar na área indicada ou selecionar as imagens do computador e arrastar para a área indicada.</p>
                    <p>Caso tenha digitado algum dado errado no cadastro do equipamento, é possível alterar os dados através da <strong>Listagem</strong> no menu <strong>Equipamentos</strong>. Bastando para isso selecionar o registro incorreto e logo depois clicar no botão <strong>Editar Registro</strong>.</p>
                    <p>Se tiver necessidade de excluir um equipamento o mesmo poderá ser feito através da <strong>Listagem</strong> no menu <strong>Equipamentos</strong>, como no processo anterior basta selecionar o registro desejado e clicar no botão <strong>Excluir Registro</strong>.</p>

                </div>
                <h3><a href="javascript:void(0);">Como gero uma Locação?</a></h3>
                <div>
                    <p>O sistema é separado por menus de controle específico que fica posicionado à esquerda do sistema</p>
                    <p>Para gerar uma nova Locação basta acessar o menu <strong>Locações</strong> e clicar na opção <strong>Nova Locação</strong>.</p>
                    <p>O cadastro é praticamente selecionar o cliente para qual deseja locar os equipamentos. A obra é referente ao cliente selecionado, caso não seja selecionado uma obra o pedido será realizado conforme o endereço do cliente cadastrado.</p>
                    <p>Com o cliente devidamente selecionado, basta adicionar os equipamentos para o pedido no botão [Adicionar Equipamento], especificar a quantidade e se utiliza acessórios. Os acessórios só serão adicionados se já forem previamente cadastrados na aba Equipamentos - > Acessórios e estiver relacionado com o equipamento que está sendo locado</p>
                    <p>A <b>Data da Locação</b> é preenchida automaticamente e é passível de alteração. Ao preencher a data será calculado 1 mês para a <b>Data de Devolução</b> também sendo passível de alteração. Com isso o <b>Valor</b> da locação será automaticamente calculado.</p>
                    <p>Se houver algum responsável pelo pedido, tal como um fiador, selecione o mesmo na opção <b>Responsável pela Obra</b></p>
                </div>
                <h3><a href="javascript:void(0);">Devolver um Equipamento</a></h3>
                <div>
                    <p>A devolução de Equipamentos é realizado no Menu <strong>Locações</strong> -> <strong>Devolução.</strong></p>
                    <p>Para gerar uma Devolução basta selecionar o <strong>Pedido Ativo</strong> na lista e clicar no botão <strong>[Devolver Itens]</strong>.</p>
                    <p>Os itens podem ser devolvidos todos finalizando o contrato ou manualmente fazendo o contrato permanecer em aberto para o sistema.</p>
                </div>
            </div>


        </div>

    </div>
</section>
<script>
    var e = $;
    e("#content .accordion").not(".toggle").each(function() {
        e(this).accordion()
    });
    e("#content .accordion.toggle").each(function() {
        e(this).multiAccordion()
    });
//    e("#content .tabbedBox").tabbedBox();
//    e("#content .vertical-tabs").tabbedBox({
//        header: e(".right-sidebar"),
//        content: e(".vertical-tabs")});
//    e("#content .wizard").not(".manual").wizard();
</script>