<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>RodrigoDaniel Página Pessoal - RoDa Sistemas;</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
                <!-- STYLESHEETS --><!--[if lt IE 9]><script src="../js/flot/excanvas.min.js"></script><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script><![endif]-->
        <link rel="stylesheet" type="text/css" href="/css/site/cloud-admin-frontend.css" >
        <link href="/css/fonts/font-awesome.min.css" rel="stylesheet">
        <!-- ANIMATE -->
        <link href="/css/site/animate.min.css" rel="stylesheet">
        <!-- COLORBOX -->
        <link rel="stylesheet" type="text/css" href="/css/site/colorbox.min.css" />
        <!-- CAROUSEL -->
        <link href="/css/site/carousel.css" rel="stylesheet">
        <!-- FONTS -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <!-- PAGE -->
        <div id="page">
            <!-- HEADER -->
            <?php echo $this->render("layouts/header.phtml"); ?>
            <!--/HEADER -->
            <!-- NAV-BAR -->
            <?php echo $this->render("layouts/navbar.phtml"); ?>
            <!--/NAV-BAR -->
            <?php echo $this->layout()->content; ?>
           
            <!-- FOOTER -->
            <?php echo $this->render("layouts/footer.phtml"); ?>
            <!--/FOOTER -->
        </div>
        <!--/PAGE -->

        <!-- JAVASCRIPTS -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="/js/site/jquery-1.9.1.min.js"></script>
        <script src="/js/site/jquery-migrate-1.2.1.min.js"></script>
        <script src="/js/site/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/site/waypoints.min.js"></script>
        <script type="text/javascript" src="/js/site/jquery.scrollTo.js"></script>
        <script type="text/javascript" src="/js/site/jquery.nav.js"></script>
        <script src="/js/site/jquery.isotope.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/site/imagesloaded.pkgd.min.js"></script>
        <!-- COLORBOX -->
        <script type="text/javascript" src="/js/site/jquery.colorbox.min.js"></script>
        <script src="/js/site/script.js"></script>
    </body>
</html>