<div class="grid_12 dashboard" id="4" >
    <div class="box" >
        <div class="header">
            <h2><span class="icon icon_16 equalizer"></span>Cadastros</h2>
        </div>
        <div class="buttons" style="padding-top: 8px">
            <a href="#clientes/cadastro"><span class="icon icon_16 user-green"></span>Clientes</a>
            <a href="#obras/cadastro"><span class="icon icon_16 hard-hat"></span>Obras</a>
            <a href="#equipamentos/cadastro"><span class="icon icon_16 drill"></span>Equipamento</a>



            <div class='divider-buts'></div>
            <a href="#locacoes/cadastro"><span class="icon icon_16 home-for-sale-sign"></span>Locações</a>
            <a href="#locacoes/devolucao"><span class="icon icon_16 arrow-return-180-left"></span>Devoluções</a>
            <a href="#locacoes/renovacao"><span class="icon icon_16 hourglass--plus"></span>Renovações</a>


        </div>

    </div>
</div>