<ul class="stats not-on-phone bgpage" >
    <li>
        <strong><?php echo $this->total_cliente; ?></strong>
        <small>Total Clientes</small>

    </li>
    <li>
        <strong><?php echo $this->total_pedido; ?></strong>
        <small>Pedidos Concluídos</small>


    </li>
    <li>
        <strong><?php echo $this->total_pedido_ativo; ?></strong>
        <small>Pedidos Ativos</small>

    </li>
    <li>
        <strong><?php echo $this->total_cancelado; ?></strong>
        <small>Pedidos Cancelados</small>

    </li>
    <li>
        <strong><?php echo $this->total_locado; ?></strong>
        <small>Equipamentos Locados</small>

    </li>
    <li>
        <strong><?php echo $this->total_manutencao; ?></strong>
        <small>Equipamentos Manutenção</small>

    </li>
    <li>
        <strong class="red"><?php echo $this->total_pendente; ?></strong>
        <small>Equipamentos Pendentes</small>

    </li>
</ul>