<?php if ($this->conf['img_upload'] == 'A') { ?>

    <div class="toolbox bottom">
        <div class='form-group'>


            <label class='control-label col-sm-2 right'>Enviar Imagem</label>
            <div class='col-sm-10'>

                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="input-group col-sm-12">
                        <div class="form-control uneditable-input" data-trigger="fileinput">
                            <span class="fileinput-preview"><i class="glyphicon glyphicon-file fileinput-exists"></i></span>
                            <span class="fileinput-filename">
                                <?php
                                if (isset($dadosi['nom_imagem'])) {
                                    echo $dadosi['nom_imagem'] . '.' . $dadosi['ext_imagem'];
                                }
                                else {
                                    echo "Selecione uma imagem";
                                }
                                ?>
                            </span>
                        </div>
                        <div class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Selecione uma imagem</span>
                                <span class="fileinput-exists">Mudar</span>
                                <input type="file" class="file-input" accept="image/*"  name="img_artigo" id="img_artigo" />
                            </span>
                            <button type="submit" class="btn btn-success fileinput-exists btn-upload">Enviar</button>
                            <button  type="button" class="btn btn-danger fileinput-exists btn-clear" data-dismiss="fileinput">Remover</button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>


<?php } ?>