<section id="content" class="container_12 clearfix" data-sort=true>
    <h1 class="grid_12">Reservas de Equipamentos</h1>
    <div class="grid_12">
        <div class="box">

            <div class="header">
                <span class="icon icon_header icon_16 i16_fugue_341"></span><h2>Equipamentos Reservados</h2>
            </div>

            <div class="content">
                <div class='container_12 '>
                    <div class='information'>
                        <h1 class='title'><span class='icon icon-warning-sign'></span>Sistema Demonstrativo!</h1>
                        <h2>Desculpe, mas apenas algumas áreas estão disponíveis nessa versão.</h2>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>