<div class="right-sidebar">
    <ul class="nav">

        <li class="green newbut"><a href="javascript:void(0)"><span class='icon icon-file'></span>| Novo Registro</a></li>
        <li class="grey editbut"><a href="javascript:void(0)"><span class='icon icon-edit'></span>| Editar Registro</a></li>
        <li class="red delbut"><a href="javascript:void(0)"><span class='icon icon-remove'></span>| Excluir Registro</a></li>
    </ul>
</div>
<section id="content" class="container_12 clearfix with-right-sidebar" data-sort="true">
    <h1 class="grid_12">Controle de Fornecedores</h1>
    <div class="grid_12">
        <div class="box">

            <div class="header">
                <span class="icon icon_header icon_16 i16_fugue_34"></span><h2>Listagem de Fornecedores</h2>
            </div>

            <div class="content">
                <table class="dynamic styled tbgrid" data-show-Filter-Bar="true" data-table-tools='{"display":true}' data-table-type="fornecedor" id="tbgrid">
                    <thead class="tabletools">
                    <th class='selbox' title='Marcar todos os Registros'><input type='checkbox' name='allchecks' id='allchecks' class='optcheck' value='' /></th>
                    <th class='selbox'>Cód</th>
                    <th >Nome</th>
                    <th >Categoria</th>
                    <th >CNPJ/CPF</th>
                    <th >Telefone</th>
                    <th >Cidade</th>
                    <th >UF</th>
                    </thead>
                    <tbody >

                        <tr>
                            <td  colspan="5" class="dataTables_empty">Carregando os Dados...</td>

                        </tr>

                    </tbody>
                </table>
                <div class="box dark" style="padding:4px">
                    <button class="button green newbut"><span class='icon icon-file'></span>Novo Registro</button>
                    <button class="button grey editbut"><span class='icon icon-edit'></span>Editar Registro</button>
                    <button class="button red delbut"><span class='icon icon-remove'></span>Excluir Registro</button>
                </div>
            </div>
        </div>
    </div>
</section>