<header class="navbar clearfix" id="header">
    <div class="container">
        <div class="navbar-brand">
            <!-- COMPANY LOGO -->
            <a href="/">
                <img src="/img/admin/logo.png" alt="Nutrace - Rastreamento de Produtos" class="img-responsive" height="30" width="120">
            </a>
            <!-- /COMPANY LOGO -->
            <!-- TEAM STATUS FOR MOBILE -->
            <div class="visible-xs">
                <a href="#" class="team-status-toggle switcher btn dropdown-toggle">
                    <i class="fa fa-users"></i>
                </a>
            </div>
            <!-- /TEAM STATUS FOR MOBILE -->
            <!-- SIDEBAR COLLAPSE -->
            <div id="sidebar-collapse" class="sidebar-collapse btn">
                <i class="fa fa-bars"
                   data-icon1="fa fa-bars"
                   data-icon2="fa fa-bars" ></i>
            </div>
            <!-- /SIDEBAR COLLAPSE -->
        </div>
        <!-- NAVBAR LEFT -->
        <ul class="nav navbar-nav pull-left hidden-xs" id="navbar-left">
            <li class="dropdown">
                <a href="#" class="team-status-toggle dropdown-toggle tip-bottom" data-toggle="tooltip" title="Toggle Team View">
                    <i class="fa fa-users"></i>
                    <span class="name"><?php echo $this->translate('txt_controle_usuarios'); ?></span>
                    <i class="fa fa-angle-down"></i>
                </a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-cog"></i>
                    <span class="name"><?php echo $this->translate('txt_configuracao'); ?></span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu skins">
                    <li class="dropdown-title">
                        <span><i class="fa fa-leaf"></i><?php echo $this->translate('txt_skins'); ?></span>
                    </li>
                    <li><a href="#" data-skin="default"><?php echo $this->translate('txt_skin_default'); ?></a></li>
                    <li><a href="#" data-skin="night"><?php echo $this->translate('txt_skin_night'); ?></a></li>
                    <li><a href="#" data-skin="earth"><?php echo $this->translate('txt_skin_earth'); ?></a></li>
                    <li><a href="#" data-skin="utopia"><?php echo $this->translate('txt_skin_utopia'); ?></a></li>
                    <li><a href="#" data-skin="nature"><?php echo $this->translate('txt_skin_nature'); ?></a></li>
                    <li><a href="#" data-skin="graphite"><?php echo $this->translate('txt_skin_graphite'); ?></a></li>
                </ul>
            </li>
        </ul>
        <!-- /NAVBAR LEFT -->
        <?php echo $this->render('layouts/top-nav-menu.phtml'); ?>
    </div>
    <?php echo $this->render('layouts/users-list.phtml'); ?>

</header>
<script>$(document).ready(function() {
        $(".dropdown-toggle").dropdown();
    });
</script>