<!-- PAGE HEADER-->
<div class="row">
    <div class="col-sm-12">
        <div class="page-header">
            <!-- BREADCRUMBS -->
            <?php echo $this->breadcrumb; ?>
            <div class="clearfix">
                <h3 class="content-title pull-left"><?php echo $this->translate('txt_' . $this->nom_modulo); ?></h3>
                <!-- PLUGINS -->
                <?php echo $this->plugins; ?>
                <!-- /PLUGINS -->
            </div>
            <div class="description"><?php echo $this->translate('txt_description_' . $this->nom_modulo); ?></div>
        </div>
    </div>
</div>
<!-- /PAGE HEADER -->