<section id="content" class="container_12 clearfix " data-sort="true">
    <h1 class="grid_12">Cadastrar Unidades</h1>
    <form name="fm_categoria" id="fm_categoria" action="/configuracoes/unidades-cadastro" class="grid_12 validate" method="post">
        <fieldset>
            <legend>Formulário de Unidades</legend>
            <div class="row">
                <label for="cod_unidade">
                    <strong>Cód. Modelo</strong>
                </label>
                <div>
                    <input type="text" name='cod_unidade' id='cod_unidade' readonly placeholder='Automático' value="<?php echo $this->data['cod_unidade']; ?>" />
                </div>
            </div>
            <div class="row">
                <label for="nom_unidade">
                    <strong>Unidade</strong>

                </label>
                <div>
                    <input type="text" class="tooltip" data-gravity=n title="É obrigatório informar a unidade." name='nom_unidade' id='nom_unidade' required value="<?php echo $this->data['nom_unidade']; ?>"/>
                </div>
            </div>


        </fieldset>
        <div class="buttons-box">
            <button class="button green" type="submit"><span class="icon icon-save"></span>Salvar Registro</button>
            <button class="button red" type="button" onclick="location.hash = 'configuracoes/unidades'"><span class="icon icon-remove"></span>Cancelar</button>
        </div>
    </form>
</section>