<section id="content" class="container_12 clearfix" data-sort="true">
    <h1 class="grid_12">Relatório de Equipamentos</h1>
    <form name="fm_cliente" id="fm_cliente" action="/relatorios/equipamentos" class="grid_12 validate" method="post">
        <fieldset>
            <legend>Filtros do Relatório</legend>

            <div class="row">
                <label for="cod_categoria">
                    <strong>Categoria</strong>

                </label>
                <div>
                    <select class='search' id='cod_categoria' name='cod_categoria'data-placeholder='Selecione uma Categoria' >
                        <option></option>
                        <option value="">Todos as Categorias</option>
                        <?php
                        foreach ($this->categorias as $row) {
                            ?>
                            <option value='<?php echo $row['cod_categoria'] ?>'  ><?php echo $row['nom_categoria']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row">
                <label for="ind_status">
                    <strong>Status</strong>
                </label>
                <div>
                    <select class='search' id='ind_status' name='ind_status'data-placeholder='Selecione um Status' >
                        <option></option>
                        <option value="">Todos os Status</option>
                        <option value="A">Ativos</option>
                        <option value="C">Concluídos</option>
                        <option value="I">Excluídos</option>
                    </select>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Organização do Relatório</legend>
            <div class="row">
                <label for="order_by">
                    <strong>Por Campo</strong>
                </label>
                <div>
                    <select class='search' id='order_by' name='order_by'data-placeholder='Selecione um Campo' >
                        <option></option>
                        <option value="cod_equipamento" selected="selected">Cód. Equipamento</option>
                        <option value="nom_equipamento">Nome do Equipamento</option>
                        <option value="ind_status">Status</option>
                        <option value="vlr_total">Valor do Equipamento</option>
                        <option value="vlr_locacao">Valor de Locação</option>
                        <option value="qtd_estoque_efetivo">Estoque Efetivo</option>
                        <option value="qtd_estoque_atual">Estoque Atual</option>


                    </select>
                </div>
            </div>
            <div class="row">
                <label for="ascdesc">
                    <strong>Ordem dos Resultados</strong>
                </label>
                <div>
                    <p >
                        <label for="ascdesc_0"><input type="radio" name="ascdesc" id="ascdesc_0" value="asc" checked="checked"/>Crescente</label>
                        <label for="ascdesc_1"><input type="radio" name="ascdesc" id="ascdesc_1" value="desc" />Decrescente</label>
                    </p>
                </div>
            </div>
            <p class='showinfos'></p>
            <div class="buttons-box">
                <button class="button green" type="submit"><span class="icon icon-eye-open"></span>Gerar Relatório</button>

            </div>
        </fieldset>
    </form>
</section>