<!-- SAMPLE BOX CONFIGURATION MODAL FORM-->
<div class="modal fade" id="box-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Configurações</h4>
            </div>
            <div class="modal-body">
                Em Construção
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Salvar Alterações</button>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div id="content" class="col-lg-12">
            <!-- PAGE HEADER-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header">
                        <!-- BREADCRUMBS -->
                        <ul class="breadcrumb">
                            <li>
                                <i class="fa fa-home"></i>
                                <a href="/">Home</a>
                            </li>
                            <li>
                                <a href="/publicacoes">Publicações</a>
                            </li>
                            <li>
                                <a href="/categorias">Categorias</a>
                            </li>
                            <li>Cadastro</li>
                        </ul>
                        <!-- /BREADCRUMBS -->
                        <div class="clearfix">
                            <h3 class="content-title pull-left">Categorias</h3>
                        </div>
                        <div class="description">Cadastro de Categorias para o Blog</div>
                    </div>
                </div>
            </div>
            <!-- /PAGE HEADER -->
            <!-- FORMS -->
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BASIC -->
                            <div class="box border blue">
                                <div class="box-title">
                                    <h4><i class="fa fa-bars"></i>Cadastro de Categoria</h4>
                                    <div class="tools hidden-xs">
                                        <a href="#box-config" data-toggle="modal" class="config">
                                            <i class="fa fa-cog"></i>
                                        </a>
                                        <a href="javascript:;" class="reload">
                                            <i class="fa fa-refresh"></i>
                                        </a>
                                        <a href="javascript:;" class="collapse">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                        <a href="javascript:;" class="remove">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="box-body big">
                                    <h3 class="form-title">Dados da Categoria</h3>
                                    <form role="form" method="post" action="" class="ajax-form">
                                        <?php echo $this->elements; ?>
                                        <div class="separator"></div>
                                        <button type="submit" class="btn btn-success">Salvar</button>
                                        <button type="reset" class="btn btn-warning">Cancelar</button>
                                    </form>
                                </div>
                            </div>
                            <!-- /BASIC -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>