
<div class="box border blue widget" id="widget-audio" <?php
if ($this->data['tipo_artigo'] !== 'audio' && $this->ajax !== 'true') {
    echo 'style="display:none"';
}
?>>
    <div class="box-title">
        <h4><i class="fa fa-music"></i>Audio</h4>
        <div class="tools hidden-xs">
            <a href="#box-config" data-toggle="modal" class="config">
                <i class="fa fa-cog"></i>
            </a>
            <a href="javascript:;" class="reload" data-url='audio'>
                <i class="fa fa-refresh"></i>
            </a>
            <a href="javascript:;" class="collapse">
                <i class="fa fa-chevron-up"></i>
            </a>

        </div>
    </div>
    <div class="box-body audio-body" id="audio">
        <div id="box_audio" style='min-height:200px'>

        </div>

    </div>
</div>
<script>
    $(document).ready(function() {
        // callSoundCloud();

    })


</script>