<?php
if (isset($this->data['cod_artigo'])) {
    $dbc = new Admin_Model_DbTable_Conf_Artigo();
    $dadosc = $dbc->getDados($this->data['cod_artigo']);
}
?>
<div>
    <div class="box border blue">
        <div class="box-title">
            <h4><i class="fa fa-pencil"></i>Personalização</h4>
            <div class="tools hidden-xs">
                <a href="#box-config" data-toggle="modal" class="config">
                    <i class="fa fa-cog"></i>
                </a>
                <a href="javascript:;" class="reload" data-url='background_artigo'>
                    <i class="fa fa-refresh"></i>
                </a>
                <a href="javascript:;" class="<?php
                if ($this->ajax !== 'true') {
                    echo 'expand';
                }
                else {
                    echo 'collapse';
                }
                ?>">
                    <i class="fa fa-chevron-<?php
                    if ($this->ajax !== 'true') {
                        echo 'down';
                    }
                    else {
                        echo 'up';
                    }
                    ?>"></i>
                </a>

            </div>
        </div>

        <div id="bg_control" class="box-body" <?php
        if ($this->ajax !== 'true') {
            //echo 'style="display:none"';
        }
        ?>>

            <div class="form-group">
                <label class='col-sm-2 control-label'>Imagem de Fundo
                    <?php if (isset($dadosc['bg_image'])) { ?>
                        <span class="preview-bg">
                            <img src="/<?php
                            $img = $dadosc['bg_image'];
                            $ext = substr($img, -3);
                            $imgn = str_replace('.' . $ext, '', $img);
                            echo $imgn . '_thumb.' . $ext;
                            ?>" onerror='$(this).parent().remove()'/>
                        </span>
                    <?php } ?>
                </label>
                <div class='col-sm-10'>
                    <div class="alert-block progress-box" id='pgbar-bg'>
                        <span class='percent-status'></span>
                        <div class='progress progress-striped active'>
                            <span class='sr-only percent'></span>
                            <div class='progress-bar bar envio_bar'  role='progressbar' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100'></div>

                        </div>
                    </div>
                    <div class="fileinput fileinput-new col-sm-12" data-provides="fileinput">

                        <div class="input-group">

                            <div class="form-control uneditable-input" data-trigger="fileinput">

                                <span class="fileinput-preview"><i class="glyphicon glyphicon-file fileinput-exists"></i></span>
                                <span class="fileinput-filename">
                                    <?php
                                    if (isset($dadosc['bg_image'])) {
                                        echo $dadosc['bg_image'];
                                    }
                                    else {
                                        echo "Selecione uma imagem";
                                    }
                                    ?>



                                </span>

                            </div>
                            <div class="input-group-btn">
                                <span class="btn btn-default btn-file">
                                    <span class="fileinput-new">Selecione uma imagem</span>
                                    <span class="fileinput-exists">Mudar</span>
                                    <input type="file" class="file-input" name="bgimage" id="bgimage"/>
                                </span>
                                <button type="submit" class="btn btn-success fileinput-exists btn-upload-bg">Enviar</button>
                                <button  type="button" class="btn btn-danger fileinput-exists btn-clear" data-dismiss="fileinput">Remover</button>


                            </div>
                        </div>
                        <input type="text" class="hidden-all" name="bg_image" id="bg_image" value="" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Textura de Fundo</label>
                <div class="col-sm-10">
                    <select name="bg_pattern" id="bg_pattern" class="col-sm-12" >
                        <option value="" <?php
                        if ($dadosc['bg_pattern'] == '') {
                            echo 'selected';
                        }
                        ?>>Sem Textura</option>
                                <?php for ($x = 1; $x < 29; $x++) { ?>
                            <option value="pattern<?php echo $x ?>.png" <?php
                            if ($dadosc['bg_pattern'] == 'pattern' . $x . '.png') {
                                echo 'selected';
                            }
                            ?>> Textura <?php echo $x; ?></option>
                                <?php } ?>

                    </select>
                </div>

            </div>
            <div class="clearfix"></div>
            <div class="divide-12"></div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Repetir Imagem</label>
                <div class="col-sm-4">
                    <select id="e1" class="col-sm-12 select" name="bg_repeat" id="bg_repeat">
                        <option></option>
                        <option value="no-repeat" <?php
                        if ($dadosc['bg_repeat'] == 'no-repeat' || $dadosc['bg_repeat'] == '') {
                            echo 'selected';
                        }
                        ?>>Não Repetir</option>
                        <option value="repeat" <?php
                        if ($dadosc['bg_repeat'] == 'repeat') {
                            echo 'selected';
                        }
                        ?>>Repetir</option>
                        <option value="repeat-x" <?php
                        if ($dadosc['bg_repeat'] == 'repeat-x') {
                            echo 'selected';
                        }
                        ?>>Repetir Horizontal</option>
                        <option value="repeat-y" <?php
                        if ($dadosc['bg_repeat'] == 'repeat-y') {
                            echo 'selected';
                        }
                        ?>>Repetir Vertical</option>
                    </select>
                </div>


                <label class="col-sm-2 control-label">Posição Imagem</label>
                <div class="col-sm-4">
                    <select id="e2" class="col-sm-12 select" name="bg_position" id="bg_position">
                        <option></option>
                        <option value="left" <?php
                        if ($dadosc['bg_position'] == 'left' || $dadosc['bg_position'] == '') {
                            echo 'selected';
                        }
                        ?>>Esquerda</option>
                        <option value="right" <?php
                        if ($dadosc['bg_position'] == 'right') {
                            echo 'selected';
                        }
                        ?>>Direita</option>
                        <option value="center" <?php
                        if ($dadosc['bg_position'] == 'center') {
                            echo 'selected';
                        }
                        ?>>Centro</option>
                        <option value="top" <?php
                        if ($dadosc['bg_position'] == 'top') {
                            echo 'selected';
                        }
                        ?>>Topo</option>
                        <option value="bottom" <?php
                        if ($dadosc['bg_position'] == 'bottom') {
                            echo 'selected';
                        }
                        ?>>Rodapé</option>
                    </select>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="divide-12"></div>

            <div class="form-group">
                <label class="control-label col-sm-2">Tamanho da Imagem</label>
                <div class="col-sm-4">
                    <select id="e3" class="col-sm-12 select" name="bg_size" id="bg_size">
                        <option></option>
                        <option value="100%" <?php
                        if ($dadosc['bg_size'] == '100%') {
                            echo 'selected';
                        }
                        ?>>Tela Inteira</option>
                        <option value="auto" <?php
                        if ($dadosc['bg_size'] == 'auto' || $dadosc['bg_size'] == '') {
                            echo 'selected';
                        }
                        ?>>Tamanho Real</option>
                    </select>
                </div>

                <label class="col-sm-2 control-label">Cor do Fundo</label>
                <div class="col-sm-4">
                    <div class='col-sm-12'>
                        <div id="color-pickers" class="colorpikerpv" style="background-color: <?php
                        if (isset($dadosc['bg_color'])) {
                            echo $dadosc['bg_color'];
                        }
                        else {
                            echo 'rgba(255,255,255,1)';
                        }
                        ?>"></div>
                        <input type="text" name="bg_color" id="bg_color" class="form-control color-picker" value="<?php
                        if (isset($dadosc['bg_color'])) {
                            echo $dadosc['bg_color'];
                        }
                        else {
                            echo 'rgba(255,255,255,1)';
                        }
                        ?>" data-color-format="rgba">
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="divide-12"></div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Cor de Fundo dos Contadores</label>
                <div class="col-sm-4">
                    <div class='col-sm-12'>
                        <div id="color-pickers"  class="colorpikerpv" style="background-color: <?php
                        if (isset($dadosc['bgcolor_meta'])) {
                            echo $dadosc['bgcolor_meta'];
                        }
                        else {
                            echo '#1e73be';
                        }
                        ?>"></div>
                        <input type="text" name="bgcolor_meta" id="bgcolor_meta" class="form-control color-picker" value="<?php
                        if (isset($dadosc['bgcolor_meta'])) {
                            echo $dadosc['bgcolor_meta'];
                        }
                        else {
                            echo '#1e73be';
                        }
                        ?>" data-color-format="hex">
                    </div>
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Posição Barra Lateral</label>
                <div class="col-sm-4">
                    <div class='col-sm-12'>
                        <label class="radio-inline">
                            <input type="radio" class="uniform" name="sidebar" value="left" <?php
                            if ($dadosc['sidebar'] == 'left' || $dadosc['sidebar'] == '') {
                                echo 'checked';
                            }
                            ?>>


                            Esquerda
                        </label>
                        <label class="radio-inline">
                            <input type="radio" class="uniform" name="sidebar" value="right" <?php
                            if ($dadosc['sidebar'] == 'right') {
                                echo 'checked';
                            }
                            ?>>
                            Direita
                        </label>
                    </div>
                </div>

            </div>
            <div class="clearfix"></div>
            <div class="divide-12"></div>
        </div>


    </div>
</div>
<script>
<?php if (!isset($this->ajax)) { ?>
        $(document).ready(function() {
<?php } ?>

        artigos.bgbox();
        //CKEDITOR.replace($(".ckeditor").attr('id'), {});
<?php if (!isset($this->ajax)) { ?>
        })
<?php } ?>
</script>