<?php
if (isset($this->data['cod_artigo'])) {
    $db = new Admin_Model_DbTable_CategoriaArtigo();
    $return = $db->getDados($this->data['cod_artigo']);


    $caArray = array();
    $x = 0;

    foreach ($return as $row) {
        $caArray[$x] = $row['cod_categoria'];
        $x++;
    }
}
else {
    $caArray = array();
}
?>

<div class="box border orange">
    <div class="box-title">
        <h4><i class="fa fa-caret-square-o-up"></i>Categorias</h4>
        <div class="tools hidden-xs">
            <a href="#box-config" data-toggle="modal" class="config">
                <i class="fa fa-cog"></i>
            </a>

            <a href="javascript:;" class="collapse">
                <i class="fa fa-chevron-up"></i>
            </a>

        </div>
    </div>
    <div class="box-body ">
        <div class="scroller categoria-body" data-height="190px" data-always-visible="1">
            <?php foreach ($this->categorias as $categoria) { ?>
                <div class="form-group">

                    <label class="checkbox">

                        <input type="checkbox" name="cod_categoria[]" id="cod_categoria" class='required' value="<?php echo $categoria['cod_categoria']; ?>" <?php
                        if (in_array($categoria['cod_categoria'], $caArray)) {
                            echo "checked='checked'";
                        }
                        ?>/>
                               <?php echo $categoria['nom_categoria'] ?>
                    </label>

                </div>
            <?php } ?>
        </div>

    </div>
    <div class="toolbox bottom">

        <div class="input-group">
            <input type="text" name="addcat" id="addcat" placeholder="Adicionar Categoria" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default btn-categoria" type="submit"><i class="fa fa-plus"></i></button>
            </span>
        </div>

    </div>
</div>