<div class="box border green">
    <div class="box-title">
        <h4><i class="fa fa-foursquare"></i>Formato</h4>
        <div class="tools hidden-xs">
            <a href="#box-config" data-toggle="modal" class="config">
                <i class="fa fa-cog"></i>
            </a>

            <a href="javascript:;" class="collapse">
                <i class="fa fa-chevron-up"></i>
            </a>

        </div>
    </div>
    <div class="box-body format">
        <div class="form-group">
            <label class="radio"><input type="radio" name="tipo_artigo" id="tipo_artigo" value="aside" <?php
                if ($this->data['tipo_artigo'] == 'aside' || $this->data['tipo_artigo'] == '') {
                    echo 'checked="checked"';
                }
                ?> />Padrão</label>
        </div>
        <div class="form-group">
            <label class="radio"><input type="radio" name="tipo_artigo" id="tipo_artigo" value="image" <?php
                if ($this->data['tipo_artigo'] == 'image') {
                    echo 'checked="checked"';
                }
                ?>/>Imagem</label>
        </div>
        <div class="form-group">
            <label class="radio"><input type="radio" name="tipo_artigo" id="tipo_artigo" value="gallery" <?php
                if ($this->data['tipo_artigo'] == 'gallery') {
                    echo 'checked="checked"';
                }
                ?>/>Galeria de Fotos</label>
        </div>
        <div class="form-group">
            <label class="radio"><input type="radio" name="tipo_artigo" id="tipo_artigo" value="video" <?php
                if ($this->data['tipo_artigo'] == 'video') {
                    echo 'checked="checked"';
                }
                ?>/>Vídeo</label>
        </div>
        <div class="form-group">
            <label class="radio"><input type="radio" name="tipo_artigo" id="tipo_artigo" value="audio" <?php
                                        if ($this->data['tipo_artigo'] == 'audio') {
                                            echo 'checked="checked"';
                                        }
                                        ?>/>Áudio</label>
        </div>

    </div>
</div>

