<?php

function mostraStatus($var) {
    $array = array("A" => "<i class='fa fa-check-square-o'></i> Ativo", "I" => "Inativo", "E" => "Excluído");
    return $array[$var];
}
?>
<div class="box border blueviolet">
    <div class="box-title">
        <h4><i class="fa fa-calendar"></i>Publicação</h4>
        <div class="tools hidden-xs">
            <a href="#box-config" data-toggle="modal" class="config">
                <i class="fa fa-cog"></i>
            </a>
            <a href="javascript:;" class="reload">
                <i class="fa fa-refresh"></i>
            </a>
            <a href="javascript:;" class="collapse">
                <i class="fa fa-chevron-up"></i>
            </a>

        </div>
    </div>
    <div class="box-body">

        <div class="form-group">
            Status do Artigo: <strong class="blue"><?php
                if (isset($this->data['ind_status'])) {
                    echo mostraStatus($this->data['ind_status']);
                }
                else {
                    echo "Inativo";
                }
                ?></strong> <!-- <a href="#">Alterar</a> -->
        </div>
        <div class="separator separator-widget"></div>
        <div class="form-group">
            Visibilidade: <strong class="blue"><?php
                if (isset($this->data['tipo_privacidade'])) {
                    echo $this->data['tipo_privacidade'];
                }
                else {
                    echo "<i class='fa fa-globe'></i> Pública";
                }
                ?></strong> <!-- <a href="#">Alterar</a> -->
        </div>
        <div class="separator separator-widget"></div>
        <div class="form-group">
            Publicado em: <strong class="blue"><?php
                if (isset($this->data['dta_artigo'])) {
                    echo $this->data['dta_artigo'];
                }
                else {
                    echo "Aguardando Publicação";
                }
                ?></strong> <!-- <a href="#">Alterar</a> -->

        </div>


    </div>
    <div class="toolbox bottom">
        <div class="btn-group">
            <button type="submit" class="btn btn-success submit-cadastro"><i class="fa fa-save"></i> Salvar</button>
            <button type="reset" class="btn btn-warning"><i class="fa fa-ban"></i> Cancelar</button>
        </div>
        <div class="btn-group pull-right hidden">
            <button type="button" class="btn btn-default"><i class="fa fa-eye"></i> Pré-Visualizar</button>


        </div>
    </div>


</div>