<div class="box border red">
    <div class="box-title">
        <h4><i class="fa fa-tags"></i>Tags</h4>
        <div class="tools hidden-xs">
            <a href="#box-config" data-toggle="modal" class="config">
                <i class="fa fa-cog"></i>
            </a>
            <a href="javascript:;" class="collapse">
                <i class="fa fa-chevron-up"></i>
            </a>

        </div>
    </div>
    <div class="box-body">
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Digite a Tag" value="" id="edtag">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="bttag">Adicionar</button>
                </span>


            </div>
        </div>
        <div class="form-group">

            <input type="hidden" id="e8" name="tag_artigo" class="no-border tags" value="<?php echo $this->data['tag_artigo']; ?>"/>

        </div>


    </div>
</div>
