
<div class="box border blue widget" id="widget-video" <?php
if ($this->data['tipo_artigo'] !== 'video') {
    echo 'style="display:none"';
}
?>>
    <div class="box-title">
        <h4><i class="fa fa-video-camera"></i>Vídeos</h4>

    </div>
    <div class="box-body" id="video">
        <div class="tabbable header-tabs">
            <ul class="nav nav-tabs">
                <li class="">
                    <a href="#box_tab2" data-toggle="tab" onclick="callVimeo()">
                        <i class="fa fa-vimeo-square"></i>
                        <span class="hidden-inline-mobile">Vimeo</span>
                    </a>
                </li>
                <li class="active">

                    <a href="#box_tab1" data-toggle="tab" onclick="callYoutube()">
                        <i class="fa fa-youtube"></i>
                        <span class="hidden-inline-mobile">Youtube</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="box_tab1">
                    Carregando Youtube
                </div>
                <div class="tab-pane" id="box_tab2" >
                    Carregando Vimeo
                </div>
            </div>
        </div>
    </div>
</div>
