<!-- EXPORT TABLES -->
<div class="row">

    <div class="col-md-12">
        <!-- BOX -->
        <div class="box border purple">
            <div class="box-title">
                <h4><i class="fa fa-table"></i><?php echo $this->translate('txt_listagem_de') . ' ' . $this->translate('txt_' . $this->nom_modulo); ?></h4>
                <div class="tools hidden-xs">
                    <a href="#box-config" data-toggle="modal" class="config">
                        <i class="fa fa-cog"></i>
                    </a>
                    <a href="javascript:;" class="reload">
                        <i class="fa fa-refresh"></i>
                    </a>
                    <a href="javascript:;" class="collapse">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a href="javascript:;" class="remove">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="box-body">
                <table id="datatable" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkboxes" id="checkboxes" /></th>
                            <?php foreach ($this->campos as $campos) { ?>
                                <th><?php echo $this->translate($campos['nome']); ?></th>
                            <?php } ?>
                            <th class="hidden-xs"><?php echo $this->translate("txt_controles"); ?></th>
                        </tr>
                    </thead>

                </table>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- /BOX -->
    </div>
</div>
<!-- /EXPORT TABLES -->
<div class="footer-tools">
    <span class="go-top">
        <i class="fa fa-chevron-up"></i> Topo
    </span>
</div>
<script>

    $(document).ready(function() {
        $("#datatable").dataTable({
            "aLengthMenu": [
                [50, 100, 200, 350, 500],
                [50, 100, 200, 350, 500] // change per page values here
            ],
            // set the initial value
            "iDisplayLength": 50,
            "sPaginationType": "bootstrap",
            "sDom": "<'row-fluid'<'col-md-11'<'col-md-4'l><'col-md-8'f>><'col-md-1 right'T>r>t<'row-fluid'<'col-md-6'i><'col-md-6'p>>",
            oTableTools: {
                aButtons: [{
                        "sExtends": "collection",
                        "sButtonText": 'Salvar <span class="caret" />',
                        "aButtons": ["csv", {
                                "sExtends": "xls",
                                "oSelectorOpts": {filter: 'applied', order: 'current'},
                                "sFileName": $('#nom_modulo').val() + ".xls"},
                            {
                                "sExtends": "pdf",
                                "oSelectorOpts": {filter: 'applied', order: 'current'},
                                "sPdfOrientation": "landscape",
                                "sFileName": $('#nom_modulo').val() + ".pdf"}]
                    }],
                sSwfPath: "/js/admin/plugins/data-tables/extra/euquefiz.swf"
            },
            "oLanguage": {
                "sLengthMenu": "_MENU_ Registros por paginas",
                "sInfo": "Visualizando _START_ - _END_ de _TOTAL_",
                "sInfoEmpty": "Visualizando 0 - 0 de 0",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sSearch": "Pesquisar:",
                "sZeroRecords": "Nao foram encontrados registros.",
                "sInfoFiltered": "(Filtrado de _MAX_ registros)",
                "oPaginate": {
                    "sPrevious": "Anterior",
                    "sNext": "Proximo"

                }
            },
            "aoColumnDefs": [
                {
                    'bSortable': false, 'aTargets': [0]
                },
                {
                    "bSearchable": false, "aTargets": [0]
                }
            ],
            "aaSorting": [[1, "desc"]], // set first column as a default sort by asc
            "processing": false,
            "serverSide": false,
            "ajax": $.fn.dataTable.pipeline({
                url: '/admin/grid/list/t/<?php echo $this->nom_modulo; ?>',
                pages: 1 // number of pages to cache
            }),
        });
    });

</script>
