<section id="content" class="container_12 clearfix" data-sort="true">
    <h1 class="grid_12">Listagem de Estoques</h1>
    <div class="grid_12">
        <div class="box">

            <div class="header">
                <span class="icon icon_header icon_16 i16_fugue_23a"></span><h2>Listagem de Estoques</h2>
            </div>

            <div class="content">
                <table class="dynamic styled tbgrid" data-show-Filter-Bar="true" data-table-tools='{"display":true}' data-table-type="estoque" id="tbgrid">
                    <thead class="tabletools">
                    <th class='selbox' title='Marcar todos os Registros'><input type='checkbox' name='allchecks' id='allchecks' class='optcheck' value='' /></th>
                    <th class='selbox'>Cód</th>
                    <th >Categoria</th>
                    <th >Total</th>
                    <th >Disponíveis</th>
                    <th >Locados</th>
                    <th >Manutenção</th>
                    <th >Atrasados</th>

                    </thead>
                    <tbody >

                        <tr class="selrows">
                            <td  colspan="5" class="dataTables_empty">Carregando os Dados...</td>

                        </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>

</section>