<!-- DATE RANGE PICKER -->
<span class="date-range pull-right">
    <div class="btn-group">
        <a class="js_update btn btn-default" href="#">Hoje</a>
        <a class="js_update btn btn-default" href="#">Últimos 7 Dias</a>
        <a class="js_update btn btn-default hidden-xs" href="#">Último Mês</a>

        <a id="reportrange" class="btn reportrange">
            <i class="fa fa-calendar"></i>
            <span></span>
            <i class="fa fa-angle-down"></i>
        </a>
    </div>
</span>
<!-- /DATE RANGE PICKER -->