<div class="right-sidebar">
    <ul class="nav">

        <li class="grey devolveequip"><a href="javascript:void(0)"><span class='icon icon-refresh'></span>| Devolver Manualmente</a></li>


    </ul>
</div>
<section id="content" class="container_12 clearfix with-right-sidebar" data-sort="true">
    <h1 class="grid_12">Cadastrar Devolução</h1>
    <form name="fm_cliente" id="fm_cliente" action="/locacoes/devolver" class="grid_12 validate" method="post">
        <fieldset>
            <legend>Formulário de Devolução</legend>
            <div class="row">
                <label for="cod_locacao">
                    <strong>Cód. Locação</strong>
                </label>
                <div>
                    <h1 class="header">
                        <?php echo $this->data['cod_locacao']; ?>
                    </h1>
                    <input type="hidden" name='cod_locacao' id='cod_locacao' placeholder='Automático' value="<?php echo $this->data['cod_locacao']; ?>" />
                </div>
            </div>
            <div class="row">
                <label for="cod_cliente">
                    <strong>Nome do Cliente</strong>
                    <small>ou Razão Social</small>
                </label>
                <div><h1 class="header">
                        <?php
                        echo $this->data['nom_cliente'];
                        ?>
                    </h1>


                </div>
            </div>
            <div class="row">
                <label for="cod_obra">
                    <strong>Obra</strong>


                </label>

                <div><h1 class="header">
                        <?php
                        echo $this->data['des_obra'];
                        ?>
                    </h1>


                </div>
            </div>
            <div class='row'>
                <label for='list_equipamentos'>
                    <strong>Equipamentos</strong>
                </label>
                <div>
                    <div class='listequip grid_12'>
                        <div class='box'>
                            <div class="header">
                                <span class="icon icon_header icon_16 i16_list"></span><h2>Listagem de Equipamentos</h2>
                                <ul class="nav tabletools">
                                    <li class="grey devolveequip"><a href="javascript:void(0)"><span class='icon icon-refresh'></span>Devolver Manualmente</a></li>

                                </ul>
                            </div>
                            <table class='styled dynamic' id='tbgrid' data-table-simple='true'>
                                <thead class='equiplist'>
                                <th style="width:10px!important">#</th>
                                <th style="width:10px!important">Qtd</th>
                                <th>Equipamento</th>
                                <th>Vlr. Locação</th>
                                <th>Vlr. Total</th>
                                </thead>
                                <?php
                                if (count($this->dataEquip) > 0) {
                                    foreach ($this->dataEquip as $row) {
                                        ?>
                                        <tr class='selrows'>
                                            <td ><input type="checkbox" name="codequip[]" class='optcheck' id="cod_equipamento_1" value="<?php echo $row['cod_equipamento_locacao'] ?>" /></td>
                                            <td ><?php echo $row['qtd_equipamento'] ?></td>
                                            <td><?php echo $row['nom_equipamento'] ?></td>
                                            <td><?php echo $row['vlr_locacao'] ?></td>
                                            <td><?php echo $row['vlr_total'] ?>
                                                <input type="hidden" name="cequip[]" id="cequip" value="<?php echo $row['cod_equipamento'] ?>">
                                                <input type="hidden" name="qequip[]" id="qequip" value="<?php echo $row['qtd_equipamento'] ?>">
                                                <input type="hidden" name="vequip[]" id="vequip" value="<?php echo $row['vlr_locacao'] ?>">
                                                <input type="hidden" name="vequipt[]" id="vequip" value="<?php echo $row['vlr_total'] ?>">
                                            </td>


                                        </tr>
                                        <?php
                                    }
                                }
                                ?>


                            </table>

                        </div>
                    </div>

                </div>
            </div>
            <div class='row'>
                <label for='dta_locacao' >
                    <strong>Data Locação</strong>
                </label>
                <div class="readonly">
                    <?php echo $this->formataData($this->data['dta_locacao']); ?>
                </div>
            </div>
            <div class='row'>
                <label for='dta_devolucao'>
                    <strong>Data Devolução</strong>
                </label>
                <div>
                    <p>
                        <input type='date' name='dta_devolucao' id='dta_devolucao' class='mask date' data-mask='99/99/9999'  value="<?php echo $this->formataData($this->data['dta_devolucao']); ?>" data-valor="<?php echo $this->formataData($this->data['dta_devolucao']); ?>"/>
                    </p>
                </div>
            </div>
            <div class='row'>
                <label for='vlr_total'>
                    <strong>Valor Total</strong>
                </label>
                <div>
                    <p><label class='inline' style="padding-top:6px;"><strong>R$</strong></label><input style='padding-left: 24px' type="text" class="money numeric" name="vlr_total" id="vlr_locacao" value="<?php echo $this->data['vlr_total']; ?>"/></p>
                </div>
            </div>


        </fieldset>
        <div class="buttons-box">
            <button class="button green" type="submit"><span class="icon icon-save"></span>Devolver Equipamentos e Concluir Pedido</button>
            <button class="button red" type="button" onclick="location.hash = 'locacoes/devolucao'"><span class="icon icon-remove"></span>Cancelar</button>
        </div>
    </form>
</section>
<script>
    coringa_registro.devolucao();
</script>